//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compucare.Enquire.Common.PersistenceModule {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Scripts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Scripts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Compucare.Enquire.Common.PersistenceModule.Scripts", typeof(Scripts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE DataItem_Group
        ///(
        ///	Identifier INTEGER PRIMARY KEY AUTOINCREMENT,
        ///	RemoteIdentifier INTEGER,
        ///	DisplayName TEXT
        ///);
        ///
        ///CREATE TABLE DataItem_Institute
        ///(
        ///	Identifier INTEGER PRIMARY KEY AUTOINCREMENT,
        ///	RemoteIdentifier INTEGER,
        ///	DisplayName TEXT,
        ///	InstituteGroup TEXT
        ///);
        ///
        ///CREATE TABLE DataItem_User
        ///(
        ///	Identifier INTEGER PRIMARY KEY AUTOINCREMENT,
        ///	RemoteIdentifier INTEGER,
        ///	GroupIdentifer INTEGER,
        ///	InstituteIdentifier INTEGER,
        ///	Tag TEXT,
        ///	Finished INTEGER,
        ///	Status INTEGER,
        ///	Remo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateDataSourcePersitence {
            get {
                return ResourceManager.GetString("CreateDataSourcePersitence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE LocalisableDataItem_Question
        ///(
        ///	Identifier INTEGER PRIMARY KEY AUTOINCREMENT,
        ///	RemoteIdentifier INTEGER,
        ///	DisplayName TEXT,
        ///	Type TEXT,
        ///	AnswerList TEXT,
        ///	Tag TEXT
        ///);
        ///
        ///CREATE TABLE LocalisableDataItem_Question_Aliases
        ///(
        ///	QuestionIdentifier INTEGER,
        ///	Alias TEXT
        ///);
        ///
        ///CREATE TABLE LocalisableDataItem_Question_Translations
        ///(
        ///	QuestionIdentifier INTEGER,
        ///	Language TEXT,
        ///	DisplayName TEXT,
        ///	AnswerList TEXT
        ///);.
        /// </summary>
        internal static string CreateDataSourceServer {
            get {
                return ResourceManager.GetString("CreateDataSourceServer", resourceCulture);
            }
        }
    }
}
