//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compucare.Enquire.Legacy.Umfrage2Lib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Compucare.Enquire.Legacy.Umfrage2Lib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap arrow_down_3 {
            get {
                object obj = ResourceManager.GetObject("arrow-down-3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_up_3 {
            get {
                object obj = ResourceManager.GetObject("arrow-up-3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bar_ico {
            get {
                object obj = ResourceManager.GetObject("bar-ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap baro_ico {
            get {
                object obj = ResourceManager.GetObject("baro-ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap excel {
            get {
                object obj = ResourceManager.GetObject("excel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap gaps_ico {
            get {
                object obj = ResourceManager.GetObject("gaps-ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap list_add {
            get {
                object obj = ResourceManager.GetObject("list-add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap list_remove {
            get {
                object obj = ResourceManager.GetObject("list-remove", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap matrix_ico {
            get {
                object obj = ResourceManager.GetObject("matrix-ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mgap_ico {
            get {
                object obj = ResourceManager.GetObject("mgap-ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap office_chart_line_stacked {
            get {
                object obj = ResourceManager.GetObject("office-chart-line-stacked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap percent_ico {
            get {
                object obj = ResourceManager.GetObject("percent-ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pot_ico {
            get {
                object obj = ResourceManager.GetObject("pot-ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap radar_ico {
            get {
                object obj = ResourceManager.GetObject("radar-ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shell32_dll_I0005_0409 {
            get {
                object obj = ResourceManager.GetObject("shell32.dll_I0005_0409", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shell32_dll_I0017_0409 {
            get {
                object obj = ResourceManager.GetObject("shell32.dll_I0017_0409", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shell32_dll_I001c_0409 {
            get {
                object obj = ResourceManager.GetObject("shell32.dll_I001c_0409", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shell32_dll_I002c_0409 {
            get {
                object obj = ResourceManager.GetObject("shell32.dll_I002c_0409", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shell32_dll_I0098_0409 {
            get {
                object obj = ResourceManager.GetObject("shell32.dll_I0098_0409", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shell32_dll_I009c_0409 {
            get {
                object obj = ResourceManager.GetObject("shell32.dll_I009c_0409", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shell32_dll_I00a7_0409 {
            get {
                object obj = ResourceManager.GetObject("shell32.dll_I00a7_0409", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shell32_dll_I00e7_0409 {
            get {
                object obj = ResourceManager.GetObject("shell32.dll_I00e7_0409", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shell32_dll_I00f0_0409 {
            get {
                object obj = ResourceManager.GetObject("shell32.dll_I00f0_0409", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shell32_dll_I00f6_0409 {
            get {
                object obj = ResourceManager.GetObject("shell32.dll_I00f6_0409", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shell32_dll_I00fd_0409 {
            get {
                object obj = ResourceManager.GetObject("shell32.dll_I00fd_0409", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shell32_dll_I010e_0409 {
            get {
                object obj = ResourceManager.GetObject("shell32.dll_I010e_0409", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shell32_dll_I0112_0409 {
            get {
                object obj = ResourceManager.GetObject("shell32.dll_I0112_0409", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shell32_dll_I0113_0409 {
            get {
                object obj = ResourceManager.GetObject("shell32.dll_I0113_0409", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shell32_dll_I0141_0409 {
            get {
                object obj = ResourceManager.GetObject("shell32.dll_I0141_0409", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shell32_dll_I0144_0409 {
            get {
                object obj = ResourceManager.GetObject("shell32.dll_I0144_0409", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shell32_dll_I416b_0409 {
            get {
                object obj = ResourceManager.GetObject("shell32.dll_I416b_0409", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shell32_dll_I416d_0409 {
            get {
                object obj = ResourceManager.GetObject("shell32.dll_I416d_0409", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shell32_dll_I416e_0409 {
            get {
                object obj = ResourceManager.GetObject("shell32.dll_I416e_0409", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shell32_dll_I4170_0409 {
            get {
                object obj = ResourceManager.GetObject("shell32.dll_I4170_0409", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shell32_dll_I4173_0409 {
            get {
                object obj = ResourceManager.GetObject("shell32.dll_I4173_0409", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shell32_dll_I4179_0409 {
            get {
                object obj = ResourceManager.GetObject("shell32.dll_I4179_0409", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shell321 {
            get {
                object obj = ResourceManager.GetObject("shell321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shell322 {
            get {
                object obj = ResourceManager.GetObject("shell322", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shell323 {
            get {
                object obj = ResourceManager.GetObject("shell323", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shell324 {
            get {
                object obj = ResourceManager.GetObject("shell324", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tacho_ico {
            get {
                object obj = ResourceManager.GetObject("tacho-ico", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
